# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @skip global
global: {}

# Override the "name" value, which is used to annotate some of
# the resources that are created by this Chart (using "app.kubernetes.io/name").
# +docs:property
nameOverride: ""

# Override the "fullname" value. This value is used as part of
# most of the names of the resources created by this Helm chart.
# +docs:property
fullnameOverride: ""

# This namespace allows you to define where the services are installed into.
# If not set then they use the namespace of the release.
# This is helpful when installing a chart dependency (sub chart).
namespace: ""

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  # The container registry to pull the image from.
  # For example:
  #   registry: kms.common.repositories.cloud.sap
  #   repository: cmk
  # +docs:property
  registry: ghcr.io/openkcm

  # The container image
  # +docs:property
  repository: gateway-extension

  # Override the image tag to deploy by setting this variable.
  # If no value is set, the chart's appVersion is used.
  # +docs:property
  #tag: 1.0.0

  # Setting a digest will override any tag.
  # +docs:property
  digest: sha256:c65465af0d457efa8ded89c6b552cad85496fa7c7988a593ccfc6df2be859324

  # Kubernetes imagePullPolicy.
  pullPolicy: IfNotPresent

  # Setting the arguments for the container
  # +docs:property
  args:
  - --graceful-shutdown=5
  - --graceful-shutdown-message="Graceful shutdown in %d seconds"

  command: "./gateway-extension"


# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
#    - name: "registry-access"


# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations:
  linkerd.io/inject: enabled

# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
#  fsGroupChangePolicy: OnRootMismatch
#  runAsUser: 1000
#  runAsGroup: 1000
#  fsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

podDisruptionBudget:
  # Enable or disable the PodDisruptionBudget resource.
  #
  # This prevents downtime during voluntary disruptions such as during a Node upgrade.
  # For example, the PodDisruptionBudget will block `kubectl drain`
  # Pod is currently running.
  enabled: false

  # This configures the minimum available pods for disruptions. It can either be set to
  # an integer (e.g. 1) or a percentage value (e.g. 25%).
  # It cannot be used if `maxUnavailable` is set.
  # +docs:property
  # +docs:type=unknown
  # minAvailable: 1

  # This configures the maximum unavailable pods for disruptions. It can either be set to
  # an integer (e.g. 1) or a percentage value (e.g. 25%).
  # it cannot be used if `minAvailable` is set.
  # +docs:property
  # +docs:type=unknown
  # maxUnavailable: 1

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # Enablement of service creation; Not needed when using unix socket listener
  enabled: true
  # Labels to add to the service
  labels: {}
  # Annotations to add to the service
  annotations: {}
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  ports:
    - port: 9092
      protocol: TCP
      targetPort: http-grpc
      name: http-grpc


# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /probe/liveness
    port: http-status
    scheme: HTTP
  failureThreshold: 1
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /probe/readiness
    port: http-status
    scheme: HTTP
  failureThreshold: 1
  periodSeconds: 10

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Additional init containers on the output Deployment definition.
extraInitContainers: []

# Additional containers on the output Deployment definition.
extraContainers: []

# Additional volumes on the output Deployment definition.
extraVolumes: []
#  - name: gateway-extension-socket-dir
#    hostPath:
#      path: "/tmp/public/run/envoy/gateway/sockets"
#      type: DirectoryOrCreate

# Additional volumeMounts on the output Deployment definition.
extraVolumeMounts: []
#  - name: gateway-extension-socket-dir
#    mountPath: "/run/envoy/gateway/sockets"
#    readOnly: false

# Additional ens on the output Deployment definition.
extraEnvs: []
# Additional envsFrom on the output Deployment definition.
extraEnvsFrom: []

nodeSelector: {}

tolerations: []

extraPorts:
  - name: http-status
    containerPort: 8888
    protocol: TCP
  - name: http-grpc
    containerPort: 9092
    protocol: TCP

affinity: {}
#affinity:
#  podAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      - labelSelector:
#          matchLabels:
#            control-plane: envoy-gateway
#        topologyKey: "kubernetes.io/hostname"
#  podAntiAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      - labelSelector:
#          matchLabels:
#            app.kubernetes.io/component: gateway-extension
#        topologyKey: "kubernetes.io/hostname"


# When running as non-root, needed to ensure the socket path has the correct permissions.
# Set runAsUser to a non-zero value in podSecurityContext to run as non-root user.
  ## @param fsGroupFix.image.registry The OCI registry to pull the image from
  ## @param fsGroupFix.image.repository The repository within the registry
  ## @param fsGroupFix.image.pullPolicy The image pull policy
  ## @param fsGroupFix.image.tag Overrides the image tag whose default is the chart appVersion
##

fsGroupFix: {}
#fsGroupFix:
#   image:
#    registry: docker.io
#    repository: bash
#    pullPolicy: Always
#    tag: 5.2.37

  ## @param fsGroupFix.resources Specify resource needs as per https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
#  resources: {}


#socket:
#  path: /run/envoy/gateway/sockets/extension.sock
#  volumeMountName: gateway-extension-socket-dir

config:
  isImmutable: false

  # Environment where the application is running
  environment: production
  # Labels associated to metrics, traces and logs
  labels: {}

  listener:
    type: "tcp" # one of: tcp, unix
    tcp:
      address: ":9092"
#    unix:
#      socketPath: "/run/envoy/gateway/sockets/extension.sock"

  grpcClientAttributes:
    keepaliveTimeSec: 1
    keepaliveTimeoutSec: 1

  status:
    enabled: true
    address: ":8888"
    profiling: true

  # This does set the logger configuration
  # +docs:property
  logger:
    level: debug # one of: debug, info, warn, error
    # Format of the logs
    format: json # one of: json, text
    formatter:
      time:
        type: unix # one of: pattern, unix
        # Used only when the property type: pattern
        # Should follow golang time pattern
        # Default value time.RFC3339.
        pattern: "Mon Jan 02 15:04:05 -0700 2006"
        # Used only when the property type: unix
        # Time units are "1ns", "1us" (or "1µs"), "1ms", "1s"
        # Default value 1s.
        precision: 1s
      fields:
        # Field names (this way the field name can be changed) to be used on log records; These are their defaults.
        error: "error"
        message: "msg"
        level: "level"
        time: "time"
        # Fields names used by OTEL to track the Trace and Span ID
        otel:
          traceID: "trace.id" # Default is TraceID
          spanID: "span.id" # Default is SpanID
        masking:
          # All fields under PII, the formatters will mask the value and keeping first 4 original characters
          pii:
            - email
            - ip-address
          # All fields under other, the formatters will mask the value, using given mask.
          other:
            jwt-token: "*****"
