name: ci
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive

      - name: Generate Build Version
        uses: hashicorp/actions-generate-metadata@main
        id: execute
        with:
          repositoryOwner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          version: cat VERSION
          product: gateway-extension
          metadataFileName: ${{ github.workspace }}/build_version.json

      - name: Print Build Version
        shell: bash
        run: cat ${{ github.workspace }}/build_version.json

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: go.mod

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: task validate
        run: task validate --verbose

      - name: task test
        run: task test --verbose
